### ISSUE TITLE
file `repl/xmlpubtk/loadqueue/LoadQueue.jar` is corrupt

### ISSUE THREAD

**Issue by frostmar** [IBM/db2-samples#71]
File /repl/xmlpubtk/loadqueue/LoadQueue.jar seems to be corrupt or non-standard in some way

**Evidence:**
download https://github.com/IBM/db2-samples/blob/master/repl/xmlpubtk/loadqueue/LoadQueue.jar
inspect with - 

```
# jar tf /tmp/LoadQueue.jar
java.util.zip.ZipException: invalid END header (bad central directory offset)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.util.zip.ZipFile.<init>(ZipFile.java:143)
	at sun.tools.jar.Main.list(Main.java:1127)
	at sun.tools.jar.Main.run(Main.java:305)
	at sun.tools.jar.Main.main(Main.java:1300)

# file /tmp/LoadQueue.jar
/tmp/LoadQueue.jar: Java archive data (JAR)
```

**Comment by kdrodger** [comment]
Just confirming that yes, I'm seeing the same behaviour.  Will take a look to see what's gone wrong and hopefully it can be fixed relatively easily.

**Comment by kdrodger** [comment]
After digging back through the history this seems to have been the case for many, many years and releases, although I think I've found an old copy that suggests the intended contents were only the single .class file plus a simple manifest.

**Comment by hdonnay** [comment]
I opened it up and figured out why the file is wrong, at least: https://github.com/quay/claircore/pull/1049#issuecomment-1710330904

Obviously I have no clue how it ended up that way.
